### PR TITLE
fix newListener and removeListener stacking on world change - don't know if this has any unintended side effects

### LINKED ISSUE #1719: newListener and removeListener stacking up on world change
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.2.0
 - server: paper 1.16.4
 - node: 14.15.4

## Detailed description of a problem
On world change, listeners called "newListener" and "removeListener" are added. They keep adding up on every world change until it prints an "MaxListenersExceededWarning" to my console. It only happens on world change and dimension change.
The warning is only printed once, however listeners are continuously added.
## What did you try yet?
I tried using bot.removeEventListener('newListener), however that function was not defined.

Did you try any method from the API?
I did not.
Did you try any example? Any error from those?
I used looker.js with some modifications

## Your current code
```js

const mineflayer = require('mineflayer')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node echo.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'looker',
  password: process.argv[5],
  version: '1.16.4'
})

setInterval(() => {
  console.log(bot._events)
}, 5000)

bot.on('spawn', () => {
  bot.chat('uwu')
})
bot.once('spawn', function () {
  setInterval(() => {
    const entity = bot.nearestEntity()
    if (entity !== null) {
      if (entity.type === 'player') {
        bot.lookAt(entity.position.offset(0, 1.6, 0))
      } else if (entity.type === 'mob') {
        bot.lookAt(entity.position)
      }
    }
  }, 50)
})

```

## Expected behavior
I expect to be only one "newListener" and "removeListener" and not have them stack up over time.
## Additional context
This seems to only happem on world change, or dimension change.
Running bot.quit and relogging into the server resets it.

Easiest way to reproduce it:
1. Enter nether portal
2. Teleport bot to you
3. Loop

Might help:
https://gist.github.com/U5B/2243710e2c9ccd768d8ecdd375a86d48

### PR DESCRIPTION
**Pull request by U5B**
L456 and L450 I edited

I do not know if this is the correct edit so I hope that someone can give some insight into this.

Fixes #1719

### CODE REVIEW

**Comment by U5B** [comment]
This fix does "fix" it but it causes other hidden problems when switching worlds, such as increasing the memory usage way too much so a better fix is needed.

**Review by rom1504 — CHANGES_REQUESTED** [review]
That's the wrong fix.

All these listeners should be created for the new world and removed from the old one.

For newListener you could indeed consider reusing the existing listener. That could be done by splitting the startListener function in 2

For the other listeners you do have to call the function on respawn

**Comment by U5B** [comment]
Actually I believe this only fixes dimension changes and not the actual problem. The actual problem is that we need to remove already existing newlistener and removeListener

**Comment by U5B** [comment]
To be honest, I do not understand this code enough for me to fix it. So I would like some assistance with this since I am a complete noob at javascript

**Comment by U5B** [comment]
hmm, if intensively switching worlds with this fix, the cpu goes from 0.10 to 10.0 and memory usage goes up for a short time.

Intesively switching worlds means that a command block is teleporting you immediately into the nether from the overworld and vice versa when you spawn .

File: lib/plugins/blocks.js [hunk 1]
```diff
@@ -458,24 +458,33 @@ function inject (bot, { version, storageBuilder }) {
     startListenerProxy()
   })
 
+  let listenerState = false
```
Comment (rom1504) [inline lib/plugins/blocks.js:461]: Why not store the listener instead ? It would be cleaner

Comment (U5B) [reply lib/plugins/blocks.js:461]: Could you give an example of storing the listener?

Is it like putting a variable before the listener?

Comment (U5B) [reply lib/plugins/blocks.js]: I believe this is what you mean.

File: lib/plugins/blocks.js [hunk 2]
```diff
@@ -457,20 +456,25 @@ function inject (bot, { version, storageBuilder }) {
...
     }
     // custom forwarder for custom events
     const blockUpdateRegex = /blockUpdate:\(-?\d+, -?\d+, -?\d+\)/
-    bot.on('newListener', (event, listener) => {
-      if (blockUpdateRegex.test(event)) {
-        bot.world.on(event, listener)
-      }
-    })
+    if (listenerState === undefined) {
+      listenerState = bot.on('newListener', (event, listener) => {
```
Comment (Karang) [inline lib/plugins/blocks.js:472]: You are using `listenerState` as a boolean, it would be more easy to understand if you made it more explicit. ie:
```js
if (!listenerState) {
   listenerState = true
   bot.on( // ...
```

**Review by Karang — COMMENTED** [review]
One minor comment, otherwise LGTM

File: lib/plugins/blocks.js (hunk 2 above)
Comment (Karang) [reply lib/plugins/blocks.js:472]: Edit: just saw Rom comments, I'm gonna read the discussion you had

File: lib/plugins/blocks.js [hunk 3]
```diff
@@ -457,20 +456,25 @@ function inject (bot, { version, storageBuilder }) {
     bot.world = new World(null, storageBuilder ? storageBuilder({ version: bot.version, worldName: dimensionToFolderName(packet.dimension) }) : null).sync
     startListenerProxy()
   })
-
+  let listenerState
   function startListenerProxy () {
+    if (listenerState !== undefined) {
+      bot.removeAllListeners('removeListener')
```
Comment (Karang) [inline lib/plugins/blocks.js:462]: The `newListener` event listeners should be removed as well.

File: lib/plugins/blocks.js [hunk 4]
```diff
@@ -457,20 +456,25 @@ function inject (bot, { version, storageBuilder }) {
...
       bot.world.on(event, (...args) => bot.emit(event, ...args))
     }
     // custom forwarder for custom events
     const blockUpdateRegex = /blockUpdate:\(-?\d+, -?\d+, -?\d+\)/
-    bot.on('newListener', (event, listener) => {
-      if (blockUpdateRegex.test(event)) {
-        bot.world.on(event, listener)
-      }
-    })
+    if (listenerState === undefined) {
```
Comment (Karang) [inline lib/plugins/blocks.js:471]: if the `newListener` from the previous world is removed, you don't need this if

File: lib/plugins/blocks.js (hunk 2 above)
Comment (Karang) [inline lib/plugins/blocks.js:472]: you need to store the listener (the function) if you want to be able to remove this one specifically (and avoid removing all listeners)
```js
listenerState = (event, listener) => { /* the function */}
bot.on('newListener', listenerState)
```
then you can do `bot.removeListener('newListener', listenerState)`

And do the same for the removeListener event

Comment (U5B) [reply lib/plugins/blocks.js:472]: I was experimenting with this, however it wasn't working properly with `bot.removeListener`

Comment (U5B) [reply lib/plugins/blocks.js:472]: `js
  function startListenerProxy () {
    let listener = (event, listener) => {
      if (blockUpdateRegex.test(event)) {
        bot.world.on(event, listener)
      }
    }
    bot.removeListener('removeListener', listener)
    bot.removeListener('newListener', listener)
    // standardized forwarding
    const forwardedEvents = ['blockUpdate', 'chunkColumnLoad', 'chunkColumnUnload']
    for (const event of forwardedEvents) {
      bot.world.on(event, (...args) => bot.emit(event, ...args))
    }
    // custom forwarder for custom events
    const blockUpdateRegex = /blockUpdate:\(-?\d+, -?\d+, -?\d+\)/
    bot.on('newListener', listener)
    bot.on('removeListener', listener)
  }
`

Comment (U5B) [reply lib/plugins/blocks.js:472]: This is the code that I was trying to use, however it doesn't seem to remove them properly

Comment (Karang) [reply lib/plugins/blocks.js:472]: try with
```js
  let listenerState
  function startListenerProxy () {
    if (listenerState) {
      // custom forwarder for custom events
      bot.removeListener('removeListener', listenerState)
      bot.removeListener('newListener', listenerState)
    }
    // standardized forwarding
    const forwardedEvents = ['blockUpdate', 'chunkColumnLoad', 'chunkColumnUnload']
    for (const event of forwardedEvents) {
      bot.world.on(event, (...args) => bot.emit(event, ...args))
    }
    const blockUpdateRegex = /blockUpdate:\(-?\d+, -?\d+, -?\d+\)/
    listenerState = (event, listener) => {
      if (blockUpdateRegex.test(event)) {
        bot.world.on(event, listener)
      }
    }
    bot.on('newListener', listenerState)
    bot.on('removeListener', listenerState)
  }
```

Comment (U5B) [reply lib/plugins/blocks.js:472]: Yep that code works I believe.

File: lib/plugins/blocks.js [hunk 5]
```diff
@@ -457,25 +456,28 @@ function inject (bot, { version, storageBuilder }) {
     bot.world = new World(null, storageBuilder ? storageBuilder({ version: bot.version, worldName: dimensionToFolderName(packet.dimension) }) : null).sync
     startListenerProxy()
   })
-
+  let listenerState
   function startListenerProxy () {
+    if (listenerState) {
+      // remove the forwarders if they already exist to prevent performance issues
+      bot.removeListener('removeListener', listenerState)
```
Comment (rom1504) [inline lib/plugins/blocks.js:463]: I don't understand why removing a listener does the same as adding

Comment (U5B) [reply lib/plugins/blocks.js:463]: ask node, but if I don't specify the arguments matching the listener being removed, it fails to remove it

Comment (U5B) [reply lib/plugins/blocks.js:463]: "listener argument must be of type function"

**Review by rom1504 — APPROVED** [review]
