### PR TITLE
Fix bot.equip failing with off-hand

### LINKED ISSUE #2006: bot.equip throws error when trying to equip to 'hand' from 'off-hand'
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: vanilla/spigot/paper vanilla
 - node: 14 LTS

## Detailed description of a problem
bot.equip throws error when trying to equip to 'hand' from 'off-hand'

## Code Bug
The issue is in this line https://github.com/PrismarineJS/mineflayer/blob/55247dbf39f642ab9de8ba4ad3e6682d46edee3a/lib/plugins/simple_inventory.js#L112. `bot.equip` checks for the source being > 36. This is wrong as the off-hand slot is slot 45. This causes the assertian here https://github.com/PrismarineJS/mineflayer/blob/55247dbf39f642ab9de8ba4ad3e6682d46edee3a/lib/plugins/simple_inventory.js#L54 to fail.

### PR DESCRIPTION
**Pull request by IceTank**
Fixes #2006

### CODE REVIEW

**Comment by u9g** [comment]
QuickBarCount is a constant that is equal to 9 at the top of this file, what does this fix?

File: lib/plugins/simple_inventory.js [hunk 1]
```diff
@@ -109,7 +109,7 @@ function inject (bot) {
       return
     }
 
-    if (destSlot >= QUICK_BAR_START && sourceSlot >= QUICK_BAR_START) {
+    if (destSlot >= QUICK_BAR_START > (QUICK_BAR_START + QUICK_BAR_COUNT) && sourceSlot >= QUICK_BAR_START > (QUICK_BAR_START + QUICK_BAR_COUNT)) {
```
Comment (Karang) [inline lib/plugins/simple_inventory.js:112]: `QUICK_BAR_START > (QUICK_BAR_START + QUICK_BAR_COUNT)` is always false, I suspect you meant to compare with destSlot and sourceSlot instead of QUICK_BAR_START ?

Comment (IceTank) [reply lib/plugins/simple_inventory.js]: Yes. I wanted to compare it with destSlot and sourceSlot so it is within QUICK_BAR_START and QUICK_BAR_START + QUICK_BAR_COUNT.

**Comment by IceTank** [comment]
I can look into making a test for this.

**Comment by rom1504** [comment]
tests are failing

**Comment by IceTank** [comment]
Test failing because of this issue https://github.com/PrismarineJS/prismarine-windows/issues/37
