### PR TITLE
1.16x

### LINKED ISSUE #1264: 1.16.2 and 1.16.3 support
## Versions
 - mineflayer: 2.28.1

## Detailed description of a problem
Mineflayer send strange error:
```/rbd/pnpm-volume/7fea977e-eb1c-4f5e-95e2-90b4bdff06d7/node_modules/.registry.npmjs.org/minecraft-protocol/1.16.0/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^
TypeError: Cannot read property 'fishing_bobber' of undefined
    at inject (/rbd/pnpm-volume/7fea977e-eb1c-4f5e-95e2-90b4bdff06d7/node_modules/.registry.npmjs.org/mineflayer/2.28.1/node_modules/mineflayer/lib/plugins/inventory.js:20:38)
    at /rbd/pnpm-volume/7fea977e-eb1c-4f5e-95e2-90b4bdff06d7/node_modules/.registry.npmjs.org/mineflayer/2.28.1/node_modules/mineflayer/lib/plugin_loader.js:26:7
    at Array.forEach (<anonymous>)
    at injectPlugins (/rbd/pnpm-volume/7fea977e-eb1c-4f5e-95e2-90b4bdff06d7/node_modules/.registry.npmjs.org/mineflayer/2.28.1/node_modules/mineflayer/lib/plugin_loader.js:25:13)
    at Bot.onInjectAllowed (/rbd/pnpm-volume/7fea977e-eb1c-4f5e-95e2-90b4bdff06d7/node_modules/.registry.npmjs.org/mineflayer/2.28.1/node_modules/mineflayer/lib/plugin_loader.js:12:5)
    at Object.onceWrapper (events.js:284:20)
    at Bot.emit (events.js:196:13)
    at Client.next (/rbd/pnpm-volume/7fea977e-eb1c-4f5e-95e2-90b4bdff06d7/node_modules/.registry.npmjs.org/mineflayer/2.28.1/node_modules/mineflayer/index.js:123:12)
    at Object.onceWrapper (events.js:284:20)
    at Client.emit (events.js:201:15)
```
## Your current code
```js

const Mineflayer = require('mineflayer');

var bot = Mineflayer.createBot({
    host: serverip,
    port: host,
});

client.on('message', message => {
  if(message.channel.id === "745699529596076158"){
    
  bot.chat(`${message.author.username}: ${message.content}`)  
  }
})

bot.on('chat', async (username, message) => {
if (username === bot.username) return;
await client.channels.cache.find(i => i.id === "745699529596076158").send(`${username}: ${message}`)
})

```

### PR DESCRIPTION
**Pull request by GroobleDierne**
Close #1264 

- [x] packet login

- [x] packet map chunk

- [x] packet multi block change

### CODE REVIEW

**Comment by rom1504** [comment]
can you change https://github.com/PrismarineJS/mineflayer/blob/master/lib/version.js#L3 to 1.16.3 ? that way the test will check if this works

**Review by Clashbestie — COMMENTED** [review]
Looks ok.

**Comment by rom1504** [comment]
Now once these 3 changes are done tests will pass again

**Comment by GroobleDierne** [comment]
Here is an example of the new multi_block_change packet, how can I extract the block coordinates?
```json
{
  "chunkCoordinates": { "x": -7, "z": 12, "y": 3 },
  "notTrustEdges": false,
  "records": [ 38896039, 38912422 ]
}
```

**Comment by rom1504** [comment]
https://wiki.vg/Pre-release_protocol#Multi_Block_Change

**Comment by rom1504** [comment]
> 

Each entry is composed of the block id, shifted right by 12, and the relative block position in the chunk section (4 bits for x, z, and y, from left to right).
--

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/08047cd778c35cb20cfeb7469fca9d8f1a567169/lib/plugins/blocks.js#L354

**Comment by rom1504** [comment]
https://wiki.vg/Protocol#Multi_Block_Change

**Comment by mkg20001** [comment]
I've noticed some transaction rejections with plugin inventory when equiping items that aren't in the bottom slots

**Comment by rom1504** [comment]
@mkg20001 how is this related with this PR?

**Comment by mkg20001** [comment]
Happening on 1.16.3, not sure if possibly something related to changes on that version

**Comment by rom1504** [comment]
@mkg20001 as you can see from this PR being open, 1.16.3 is not supported yet

**Comment by roobscoob** [comment]
bumping.

**Comment by GroobleDierne** [comment]
> bumping.

I'll work on that tomorrow (UTC+2).

**Comment by roobscoob** [comment]
Updates, @GroobleDierne ?

**Comment by GroobleDierne** [comment]
I'm in a hurry but I hope to have more time this weekend.

**Comment by GroobleDierne** [comment]
https://github.com/PrismarineJS/mineflayer/blob/b9682a83f243e2a5141477bdaf81c846870021e3/lib/plugins/blocks.js#L359-L364
I'm not familiar with binary operations so I don't know if I'm doing it the right way, but I've done some tests and the data seems to be consistent.

**Comment by GroobleDierne** [comment]
@rom1504 I have the impression that "map_chunk" doesn't need any modifications.

**Comment by Patbox** [comment]
I think prismarine-chunk needs still an update.

File: lib/plugins/blocks.js [hunk 1]
```diff
@@ -356,11 +356,12 @@ function inject (bot, { version, storageBuilder }) {
     for (let i = 0; i < packet.records.length; ++i) {
       const record = packet.records[i]
 
-      const blockZ = (record.horizontalPos & 0x0f)
-      const blockX = (record.horizontalPos >> 4) & 0x0f
+      const blockZ = record.horizontalPos !== undefined ? (record.horizontalPos & 0x0f) : record & 0x0f
```
Comment (rom1504) [inline lib/plugins/blocks.js:359]: can you simplify this by doing 2 blocks with a single if checking what version we are in ?
second point is
> Each entry is composed of the block id, shifted right by 12, and the relative block position in the chunk section (4 bits for x, z, and y, from left to right).

The order is x, z then y

File: test/internalTest.js [hunk 2]
```diff
@@ -153,29 +153,38 @@ mineflayer.testedVersions.forEach((supportedVersion, i) => {
...
           entityId: 0,
           levelType: 'fogetaboutit',
-          hashedSeed: [0, 0],
           gameMode: 0,
           previousGameMode: 255,
           worldNames: ['minecraft:overworld'],
-          dimensionCodec: { name: '', type: 'compound', value: { dimension: { type: 'list', value: { type: 'compound', value: [w] } } } },
-          dimension: bot.supportFeature('dimensionIsAnInt') ? 0 : 'minecraft:overworld',
+          dimensionCodec: (version.version >= 735 ? mcData.loginPacket.dimension : { name: '', type: 'compound', value: { dimension: { type: 'list', value: { type: 'compound', value: [w] } } } }),
+          dimension: (version.version >= 735 ? mcData.loginPacket.dimension : 0),
```
Comment (rom1504) [inline test/internalTest.js:171]: you can just use mcData.loginPacket instead of the big thing using w
it would be much better to put this version.version >= 735 inside support feature function (changing how it works)

File: test/internalTest.js [hunk 3]
```diff
@@ -153,29 +153,38 @@ mineflayer.testedVersions.forEach((supportedVersion, i) => {
...
           worldName: 'minecraft:overworld',
+          hashedSeed: [0, 0],
           difficulty: 0,
           maxPlayers: 20,
-          reducedDebugInfo: true,
+          reducedDebugInfo: (version.version >= 735 ? true : 1),
           enableRespawnScreen: true
-        })
+        }
+        if (version.version >= 735) { // 1.16x
```
Comment (rom1504) [inline test/internalTest.js:179]: it's not needed to define only the needed fields, it's ok to have additional fields

**Review by rom1504 — CHANGES_REQUESTED** [review]

**Comment by GroobleDierne** [comment]
Ready for merge

File: lib/supportFeature.js [hunk 4]
```diff
@@ -1,4 +1,11 @@
 const features = require('./features')
 
-module.exports = (feature, version) =>
-  features.some(({ name, versions }) => name === feature && versions.includes(version))
+module.exports = (feature, minecraftVersion) => {
+  const f = features.find(f => f.name === feature)
+
+  const currentVer = require('minecraft-data')(minecraftVersion).version.version
+  const minVer = require('minecraft-data')(f.versions[0]).version.version
```
Comment (rom1504) [inline lib/supportFeature.js:7]: Isn't this version the protocol version ? It would be better not to use that and instead use the position of the version in the array. It's better to avoid relying on this protocol version as mojang rules for updating it are not consistent.

File: lib/plugins/blocks.js [hunk 5]
```diff
@@ -356,11 +356,19 @@ function inject (bot, { version, storageBuilder }) {
...
+        blockY = record & 0x0f
+      } else {
+        blockZ = record.horizontalPos & 0x0f
+        blockX = (record.horizontalPos >> 4) & 0x0f
+        blockY = record.y
+      }
 
-      const pt = new Vec3(packet.chunkX * 16 + blockX, record.y, packet.chunkZ * 16 + blockZ)
-      updateBlockState(pt, record.blockId)
+      const pt = new Vec3((packet.chunkX !== undefined ? packet.chunkX : packet.chunkCoordinates.x) * 16 + blockX, (packet.chunkCoordinates !== undefined ? packet.chunkCoordinates.y : 0) * 16 + blockY, (packet.chunkZ !== undefined ? packet.chunkZ : packet.chunkCoordinates.z) * 16 + blockZ)
```
Comment (rom1504) [inline lib/plugins/blocks.js:370]: Could you do a similar as above if here, that would simplify the code.

File: lib/plugins/game.js [hunk 6]
```diff
@@ -12,15 +12,20 @@ function inject (bot) {
...
 
   bot._client.on('login', (packet) => {
-    bot.game.levelType = packet.levelType
+    bot.game.levelType = (packet.levelType ? packet.levelType : (packet.isFlat ? 'flat' : 'default'))
     bot.game.gameMode = parseGameMode(packet.gameMode)
     bot.game.hardcore = parseHardcore(packet.gameMode)
     if (bot.supportFeature('dimensionIsAnInt')) {
       bot.game.dimension = dimensionNames[packet.dimension]
-    } else if (bot.supportFeature('dimensionIsAString')) {
+    } else if (bot.protocolVersion < 751 && bot.supportFeature('dimensionIsAString')) {
```
Comment (rom1504) [inline lib/plugins/game.js:20]: This should be using only support feature, not protocol version

**Review by rom1504 — CHANGES_REQUESTED** [review]
Almost there, left a few comments related to the last changes @TheDudeFromCI did
Did you check that multi block change parsing is working fine in 1.16.3 ?

File: lib/supportFeature.js [hunk 7]
```diff
@@ -1,4 +1,22 @@
 const features = require('./features')
 
-module.exports = (feature, version) =>
-  features.some(({ name, versions }) => name === feature && versions.includes(version))
+function versionIndex (versionString) {
```
Comment (rom1504) [inline lib/supportFeature.js:3]: This is really slow and could be optimised by building the relevant dictionaries
Might be important as this function is called often.
In fact we may even precompute all the supported feature for the current version.
However it looks like it should work, let's optimize it in another PR

**Review by rom1504 — APPROVED** [review]

**Comment by rom1504** [comment]
Build not passing, could you have a look ?

**Review by rom1504 — APPROVED** [review]
