### PR TITLE
Fix trade tests

### LINKED ISSUE #973: Fix trading test
It was disabled for now

### PR DESCRIPTION
**Pull request by ImHarvol**
- Fixes trading tests by using a command block to spawn the villager
- Fixes a litle bug in lib/plugins/villager.js: In some versions inputItem2 is an Item instance with no atributes so the old condition tought the trade had a inputItem2 and throwed

Closes #973
Related to #1323

### CODE REVIEW

File: test/externalTests/trade.js [hunk 1]
```diff
@@ -1,27 +1,50 @@
...
-  done()
-  // TODO fix unreliable trading/trading test
-  /*
   const mcData = require('minecraft-data')(bot.version)
   const Item = require('prismarine-item')(bot.version)
 
   const villagerType = mcData.entitiesByName.villager ? 'villager' : 'Villager'
 
+  const summonCommand = bot.supportFeature('indexesVillagerRecipes')
+    ? `/summon ${villagerType} ~ ~1 ~ {NoAI:1, Offers:{Recipes:[0:{maxUses:7,buy:{id:"minecraft:emerald",Count:2},sell:{id:"minecraft:wheat",Count:2}, uses:1}]}}`
```
Comment (wvffle) [inline test/externalTests/trade.js:10]: I don't know how it works in minecraft but is `{Recipes:[0:{}]}` correct?
(Just a question)

File: test/externalTests/trade.js [hunk 2]
```diff
@@ -30,10 +53,13 @@ module.exports = () => (bot, done) => {
...
-  bot.test.setInventorySlot(36, new Item(mcData.itemsByName.emerald.id, 1, 0), (err) => {
+  bot.test.setInventorySlot(36, new Item(mcData.itemsByName.emerald.id, 64, 0), (err) => {
     assert.ifError(err)
     bot.on('entitySpawn', onEntitySpawn)
-    // The command is callibrated to be under the 100 character limit of 1.8 - 1.10:
-    bot.test.sayEverywhere(`/summon ${villagerType} 1 5 1 {Offers:{Recipes:[{buy:{id:emerald,Count:1},sell:{id:bread,Count:1}}]}}`)
-  }) */
+
+    // A command block is needed to spawn the villager due to the chat's character limit in some versions
+    bot.test.sayEverywhere(`/setblock ${commandBlockPosTxt} command_block`)
```
Comment (wvffle) [inline test/externalTests/trade.js:61]: Can we use `commandBlockPos.toArray().join('  ')` here? 

`commandBlockPosTxt` implies that  it's just a string. Better name would be `commandBlockPosArgs` but we're not using it any other part of code.

**Review by wvffle — CHANGES_REQUESTED** [review]

File: test/externalTests/trade.js (hunk 1 above)
Comment (ImHarvol) [reply test/externalTests/trade.js:10]: I dont know much either, but I've been testing it and it works!

Here's a standard villager metadata in 1.8 for reference:
```
{HurtByTimestamp:0,Attributes:[0:{Base:20.0d,Name:"generic.maxHealth"},1:{Base:0.0d,Name:"generic.knockbackResistance"},2:{Base:0.5d,Name:"generic.movementSpeed"},3:{Base:16.0d,Modifiers:[0:{UUIDMost:-3631253411971314151L,UUIDLeast:-8828509508598644614L,Amount:-0.01844724002497035d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"}],Riches:0,Invulnerable:0b,ForcedAge:0,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,DeathTime:0s,DropChances:[0:0.085f,1:0.085f,2:0.085f,3:0.085f,4:0.085f],PersistenceRequired:0b,HealF:20.0f,Age:0,Motion:[0:0.0d,1:-0.0784000015258789d,2:0.0d],Leashed:0b,UUIDLeast:-7028543208059295380L,Health:20s,Air:300s,OnGround:1b,Dimension:0,Offers:{Recipes:[0:{maxUses:7,buy:{id:"minecraft:leather",Count:11b,Damage:0s},sell:{id:"minecraft:emerald",Count:1b,Damage:0s},uses:0,rewardExp:1b},1:{maxUses:7,buy:{id:"minecraft:emerald",Count:3b,Damage:0s},sell:{id:"minecraft:leather_leggings",Count:1b,Damage:0s},uses:0,rewardExp:1b}]},Rotation:[0:0.0f,1:0.0f],Profession:4,UUIDMost:6991824022769256519L,Equipment:[0:{},1:{},2:{},3:{},4:{}],Pos:[0:-26.0987337365875d,1:4.0d,2:20.005468739674903d],Fire:-1s,CanPickUpLoot:1b,HurtTime:0s,CareerLevel:1,Career:2,Inventory:[],Willing:0b}
```

Comment (wvffle) [reply test/externalTests/trade.js:10]: weird.

**Review by rom1504 — APPROVED** [review]
